# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4cf6d90fb16a63e9e332191a66775cb3a68b934ed350e42dd699b54921afa123044a425810017f00de88e0c7cff2d08616e56ad0ebaa5b6aca8aa4edd5666ec

test:
  secret_key_base: 8e1cb0059f600e4230d4e8fd488c3bac0214d58ab4c5687f660316d721f6134b42a30896042608168f2197f1470eb6134489c488eb95a52b524b2e68a682e82f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
